export const mockSearchArticleResponse = {
  "items": [
    {
      "web_url": "https://www.nytimes.com/aponline/2018/05/27/sports/soccer/ap-soc-brazil-wcup-neymar.html",
      "snippet": "Neymar has admitted he is not 100 percent in shape after a week of training with Brazil in World Cup preparations.",
      "blog": {},
      "source": "AP",
      "multimedia": [],
      "headline": {
        "main": "Neymar Admits Not Being 100 Percent Fit Ahead of World Cup",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Neymar Admits Not Being 100 Percent Fit Ahead of World Cup",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-27T17:54:51+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Soccer",
      "byline": {
        "original": "By THE ASSOCIATED PRESS",
        "person": [],
        "organization": "THE ASSOCIATED PRESS"
      },
      "type_of_material": "News",
      "_id": "5b0af0ee068401528a2b0147",
      "word_count": 116,
      "score": 0.0025541275,
      "uri": "nyt://article/e7446e22-5997-5cb0-9c1b-31a7ecc1a953"
    },
    {
      "web_url": "https://www.nytimes.com/reuters/2018/05/27/sports/tennis/27reuters-tennis-frenchopen-order.html",
      "snippet": "World number one Rafa Nadal begins his French Open title defense on Monday with a clash against Italy's Simone Bolelli on Court Philippe-Chatrier.",
      "blog": {},
      "source": "Reuters",
      "multimedia": [],
      "headline": {
        "main": "Nadal Begins Title Defense Against Bolelli on Second Day",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Nadal Begins Title Defense Against Bolelli on Second Day",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-27T17:27:46+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Tennis",
      "byline": {
        "original": "By REUTERS",
        "person": [],
        "organization": "REUTERS"
      },
      "type_of_material": "News",
      "_id": "5b0aea94068401528a2b0139",
      "word_count": 224,
      "score": 0.0017083477,
      "uri": "nyt://article/6c811cb8-5d5a-558a-9e4d-7416ee263bf4"
    },
    {
      "web_url": "https://www.nytimes.com/reuters/2018/05/27/world/americas/27reuters-brazil-transport.html",
      "snippet": "Truck owners removed their vehicles from some key roads in Brazil overnight and early on Sunday as local and federal governments worked on a new proposal to end a nationwide protest that has caused wide disruption to transporting grains and fuel. ",
      "blog": {},
      "source": "Reuters",
      "multimedia": [],
      "headline": {
        "main": "Protesting Truckers Clear Some Roads in Brazil Amid Talks",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Protesting Truckers Clear Some Roads in Brazil Amid Talks",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-27T16:54:46+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Americas",
      "byline": {
        "original": "By REUTERS",
        "person": [],
        "organization": "REUTERS"
      },
      "type_of_material": "News",
      "_id": "5b0ae2d8068401528a2b0132",
      "word_count": 258,
      "score": 0.29232183,
      "uri": "nyt://article/16288392-00da-5539-8045-6cd71a0e48d1"
    },
    {
      "web_url": "https://www.nytimes.com/reuters/2018/05/27/sports/soccer/27reuters-soccer-worldcup-kor-son.html",
      "snippet": "Son Heung-min needs to overcome his status as a marked man after an impressive season for Tottenham Hotspur if he is to establish himself among the game's elite at the World Cup in Russia, says South Korea coach Shin Tae-yong.",
      "blog": {},
      "source": "Reuters",
      "multimedia": [],
      "headline": {
        "main": "Soccer: Son Must Step Up to Become World Cup Great, Says South Korea Coach Shin",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Soccer: Son Must Step Up to Become World Cup Great, Says South Korea Coach Shin",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-27T10:33:46+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Soccer",
      "byline": {
        "original": "By REUTERS",
        "person": [],
        "organization": "REUTERS"
      },
      "type_of_material": "News",
      "_id": "5b0a89ad068401528a2b00cf",
      "word_count": 473,
      "score": 0.0015192353,
      "uri": "nyt://article/42d768ca-5476-5ee3-b0fa-a3d7983fecd0"
    },
    {
      "web_url": "https://www.nytimes.com/aponline/2018/05/27/world/americas/ap-lt-colombia-election-glance.html",
      "snippet": "Colombia's presidential election on May 27 is the first since the government signed a peace deal with the Revolutionary Armed Forces of Colombia leading to the disarmament of some 7,000 fighters. Five candidates are running and if none gets more t...",
      "blog": {},
      "source": "AP",
      "multimedia": [],
      "headline": {
        "main": "A Glance at Colombia's Presidential Election",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "A Glance at Colombia's Presidential Election",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-27T04:04:14+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Americas",
      "byline": {
        "original": "By THE ASSOCIATED PRESS",
        "person": [],
        "organization": "THE ASSOCIATED PRESS"
      },
      "type_of_material": "News",
      "_id": "5b0a2e41068401528a2b0089",
      "word_count": 569,
      "score": 0.0012967084,
      "uri": "nyt://article/045da572-7b1d-53d3-8478-5b2b2e5ae82c"
    },
    {
      "web_url": "https://www.nytimes.com/reuters/2018/05/26/world/americas/26reuters-brazil-transport.html",
      "snippet": "A truckers protest over diesel prices in Brazil that is hurting supplies of fuel, food and medicines continued for the sixth day on Saturday despite President Michel Temer ordering the military to clear blocked roads the day before. ",
      "blog": {},
      "source": "Reuters",
      "multimedia": [],
      "headline": {
        "main": "Brazil's Truckers Protest Drags on Despite Dispatch of Military",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Brazil's Truckers Protest Drags on Despite Dispatch of Military",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-26T17:27:43+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Americas",
      "byline": {
        "original": "By REUTERS",
        "person": [],
        "organization": "REUTERS"
      },
      "type_of_material": "News",
      "_id": "5b099915068401528a2affe1",
      "word_count": 419,
      "score": 0.0015192353,
      "uri": "nyt://article/00a44401-cef3-58ac-a373-6daa8e3f8437"
    },
    {
      "web_url": "https://www.nytimes.com/2018/05/26/sports/tennis/ben-mclachlan-french-open.html",
      "snippet": "McLachlan, who represents Japan now instead of New Zealand, enters the French Open ranked 25th in doubles, despite having had 10 partners this year.",
      "print_page": "5",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [
        {
          "rank": 0,
          "subtype": "xlarge",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-articleLarge.jpg",
          "height": 422,
          "width": 600,
          "legacy": {
            "xlarge": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-articleLarge.jpg",
            "xlargewidth": 600,
            "xlargeheight": 422
          },
          "subType": "xlarge",
          "crop_name": "articleLarge"
        },
        {
          "rank": 0,
          "subtype": "wide",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-thumbWide.jpg",
          "height": 126,
          "width": 190,
          "legacy": {
            "wide": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-thumbWide.jpg",
            "widewidth": 190,
            "wideheight": 126
          },
          "subType": "wide",
          "crop_name": "thumbWide"
        },
        {
          "rank": 0,
          "subtype": "thumbnail",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-thumbStandard.jpg",
          "height": 75,
          "width": 75,
          "legacy": {
            "thumbnail": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-thumbStandard.jpg",
            "thumbnailwidth": 75,
            "thumbnailheight": 75
          },
          "subType": "thumbnail",
          "crop_name": "thumbStandard"
        },
        {
          "rank": 0,
          "subtype": "articleInline",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-articleInline.jpg",
          "height": 134,
          "width": 190,
          "legacy": {},
          "subType": "articleInline",
          "crop_name": "articleInline"
        },
        {
          "rank": 0,
          "subtype": "blog225",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-blog225.jpg",
          "height": 158,
          "width": 225,
          "legacy": {},
          "subType": "blog225",
          "crop_name": "blog225"
        },
        {
          "rank": 0,
          "subtype": "blog427",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-blog427.jpg",
          "height": 300,
          "width": 427,
          "legacy": {},
          "subType": "blog427",
          "crop_name": "blog427"
        },
        {
          "rank": 0,
          "subtype": "blog480",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-blog480.jpg",
          "height": 338,
          "width": 480,
          "legacy": {},
          "subType": "blog480",
          "crop_name": "blog480"
        },
        {
          "rank": 0,
          "subtype": "blog533",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-blog533.jpg",
          "height": 375,
          "width": 533,
          "legacy": {},
          "subType": "blog533",
          "crop_name": "blog533"
        },
        {
          "rank": 0,
          "subtype": "blogSmallInline",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-blogSmallInline.jpg",
          "height": 106,
          "width": 151,
          "legacy": {},
          "subType": "blogSmallInline",
          "crop_name": "blogSmallInline"
        },
        {
          "rank": 0,
          "subtype": "blogSmallThumb",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-blogSmallThumb.jpg",
          "height": 50,
          "width": 50,
          "legacy": {},
          "subType": "blogSmallThumb",
          "crop_name": "blogSmallThumb"
        },
        {
          "rank": 0,
          "subtype": "facebookJumbo",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-facebookJumbo.jpg",
          "height": 549,
          "width": 1050,
          "legacy": {},
          "subType": "facebookJumbo",
          "crop_name": "facebookJumbo"
        },
        {
          "rank": 0,
          "subtype": "filmstrip",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-filmstrip.jpg",
          "height": 190,
          "width": 190,
          "legacy": {},
          "subType": "filmstrip",
          "crop_name": "filmstrip"
        },
        {
          "rank": 0,
          "subtype": "hpLarge",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-hpLarge.jpg",
          "height": 287,
          "width": 511,
          "legacy": {},
          "subType": "hpLarge",
          "crop_name": "hpLarge"
        },
        {
          "rank": 0,
          "subtype": "hpSmall",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-hpSmall.jpg",
          "height": 115,
          "width": 163,
          "legacy": {},
          "subType": "hpSmall",
          "crop_name": "hpSmall"
        },
        {
          "rank": 0,
          "subtype": "jumbo",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-jumbo.jpg",
          "height": 720,
          "width": 1024,
          "legacy": {},
          "subType": "jumbo",
          "crop_name": "jumbo"
        },
        {
          "rank": 0,
          "subtype": "largeHorizontal375",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-largeHorizontal375.jpg",
          "height": 250,
          "width": 375,
          "legacy": {},
          "subType": "largeHorizontal375",
          "crop_name": "largeHorizontal375"
        },
        {
          "rank": 0,
          "subtype": "largeHorizontalJumbo",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-largeHorizontalJumbo.jpg",
          "height": 682,
          "width": 1024,
          "legacy": {},
          "subType": "largeHorizontalJumbo",
          "crop_name": "largeHorizontalJumbo"
        },
        {
          "rank": 0,
          "subtype": "largeWidescreen573",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-largeWidescreen573.jpg",
          "height": 322,
          "width": 573,
          "legacy": {},
          "subType": "largeWidescreen573",
          "crop_name": "largeWidescreen573"
        },
        {
          "rank": 0,
          "subtype": "largeWidescreen1050",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-largeWidescreen1050.jpg",
          "height": 590,
          "width": 1050,
          "legacy": {},
          "subType": "largeWidescreen1050",
          "crop_name": "largeWidescreen1050"
        },
        {
          "rank": 0,
          "subtype": "master1050",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-master1050.jpg",
          "height": 739,
          "width": 1050,
          "legacy": {},
          "subType": "master1050",
          "crop_name": "master1050"
        },
        {
          "rank": 0,
          "subtype": "master180",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-master180.jpg",
          "height": 127,
          "width": 180,
          "legacy": {},
          "subType": "master180",
          "crop_name": "master180"
        },
        {
          "rank": 0,
          "subtype": "master315",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-master315.jpg",
          "height": 222,
          "width": 315,
          "legacy": {},
          "subType": "master315",
          "crop_name": "master315"
        },
        {
          "rank": 0,
          "subtype": "master495",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-master495.jpg",
          "height": 348,
          "width": 495,
          "legacy": {},
          "subType": "master495",
          "crop_name": "master495"
        },
        {
          "rank": 0,
          "subtype": "master768",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-master768.jpg",
          "height": 540,
          "width": 768,
          "legacy": {},
          "subType": "master768",
          "crop_name": "master768"
        },
        {
          "rank": 0,
          "subtype": "master675",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-master675.jpg",
          "height": 475,
          "width": 675,
          "legacy": {},
          "subType": "master675",
          "crop_name": "master675"
        },
        {
          "rank": 0,
          "subtype": "mediumFlexible177",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-mediumFlexible177.jpg",
          "height": 125,
          "width": 177,
          "legacy": {},
          "subType": "mediumFlexible177",
          "crop_name": "mediumFlexible177"
        },
        {
          "rank": 0,
          "subtype": "mediumSquare149",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-mediumSquare149.jpg",
          "height": 149,
          "width": 149,
          "legacy": {},
          "subType": "mediumSquare149",
          "crop_name": "mediumSquare149"
        },
        {
          "rank": 0,
          "subtype": "mediumThreeByTwo210",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-mediumThreeByTwo210.jpg",
          "height": 140,
          "width": 210,
          "legacy": {},
          "subType": "mediumThreeByTwo210",
          "crop_name": "mediumThreeByTwo210"
        },
        {
          "rank": 0,
          "subtype": "mediumThreeByTwo225",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-mediumThreeByTwo225.jpg",
          "height": 150,
          "width": 225,
          "legacy": {},
          "subType": "mediumThreeByTwo225",
          "crop_name": "mediumThreeByTwo225"
        },
        {
          "rank": 0,
          "subtype": "mediumThreeByTwo440",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-mediumThreeByTwo440.jpg",
          "height": 293,
          "width": 440,
          "legacy": {},
          "subType": "mediumThreeByTwo440",
          "crop_name": "mediumThreeByTwo440"
        },
        {
          "rank": 0,
          "subtype": "mediumThreeByTwo378",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-mediumThreeByTwo378.jpg",
          "height": 252,
          "width": 378,
          "legacy": {},
          "subType": "mediumThreeByTwo378",
          "crop_name": "mediumThreeByTwo378"
        },
        {
          "rank": 0,
          "subtype": "mediumThreeByTwo252",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-mediumThreeByTwo252.jpg",
          "height": 168,
          "width": 252,
          "legacy": {},
          "subType": "mediumThreeByTwo252",
          "crop_name": "mediumThreeByTwo252"
        },
        {
          "rank": 0,
          "subtype": "miniMoth",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-miniMoth.jpg",
          "height": 70,
          "width": 151,
          "legacy": {},
          "subType": "miniMoth",
          "crop_name": "miniMoth"
        },
        {
          "rank": 0,
          "subtype": "moth",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-moth.jpg",
          "height": 151,
          "width": 151,
          "legacy": {},
          "subType": "moth",
          "crop_name": "moth"
        },
        {
          "rank": 0,
          "subtype": "popup",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-popup.jpg",
          "height": 457,
          "width": 650,
          "legacy": {},
          "subType": "popup",
          "crop_name": "popup"
        },
        {
          "rank": 0,
          "subtype": "sfSpan",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-sfSpan.jpg",
          "height": 263,
          "width": 395,
          "legacy": {},
          "subType": "sfSpan",
          "crop_name": "sfSpan"
        },
        {
          "rank": 0,
          "subtype": "slide",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-slide.jpg",
          "height": 422,
          "width": 600,
          "legacy": {},
          "subType": "slide",
          "crop_name": "slide"
        },
        {
          "rank": 0,
          "subtype": "smallSquare168",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-smallSquare168.jpg",
          "height": 168,
          "width": 168,
          "legacy": {},
          "subType": "smallSquare168",
          "crop_name": "smallSquare168"
        },
        {
          "rank": 0,
          "subtype": "smallSquare252",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-smallSquare252.jpg",
          "height": 252,
          "width": 252,
          "legacy": {},
          "subType": "smallSquare252",
          "crop_name": "smallSquare252"
        },
        {
          "rank": 0,
          "subtype": "square320",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-square320.jpg",
          "height": 320,
          "width": 320,
          "legacy": {},
          "subType": "square320",
          "crop_name": "square320"
        },
        {
          "rank": 0,
          "subtype": "square640",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-square640.jpg",
          "height": 640,
          "width": 640,
          "legacy": {},
          "subType": "square640",
          "crop_name": "square640"
        },
        {
          "rank": 0,
          "subtype": "superJumbo",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-superJumbo.jpg",
          "height": 1441,
          "width": 2048,
          "legacy": {},
          "subType": "superJumbo",
          "crop_name": "superJumbo"
        },
        {
          "rank": 0,
          "subtype": "thumbLarge",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-thumbLarge.jpg",
          "height": 150,
          "width": 150,
          "legacy": {},
          "subType": "thumbLarge",
          "crop_name": "thumbLarge"
        },
        {
          "rank": 0,
          "subtype": "tmagArticle",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-tmagArticle.jpg",
          "height": 417,
          "width": 592,
          "legacy": {},
          "subType": "tmagArticle",
          "crop_name": "tmagArticle"
        },
        {
          "rank": 0,
          "subtype": "tmagSF",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-tmagSF.jpg",
          "height": 255,
          "width": 362,
          "legacy": {},
          "subType": "tmagSF",
          "crop_name": "tmagSF"
        },
        {
          "rank": 0,
          "subtype": "verticalTwoByThree735",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-verticalTwoByThree735.jpg",
          "height": 1102,
          "width": 735,
          "legacy": {},
          "subType": "verticalTwoByThree735",
          "crop_name": "verticalTwoByThree735"
        },
        {
          "rank": 0,
          "subtype": "videoFifteenBySeven1305",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoFifteenBySeven1305.jpg",
          "height": 609,
          "width": 1305,
          "legacy": {},
          "subType": "videoFifteenBySeven1305",
          "crop_name": "videoFifteenBySeven1305"
        },
        {
          "rank": 0,
          "subtype": "videoFifteenBySeven2610",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoFifteenBySeven2610.jpg",
          "height": 1218,
          "width": 2610,
          "legacy": {},
          "subType": "videoFifteenBySeven2610",
          "crop_name": "videoFifteenBySeven2610"
        },
        {
          "rank": 0,
          "subtype": "videoHpMedium",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoHpMedium.jpg",
          "height": 211,
          "width": 375,
          "legacy": {},
          "subType": "videoHpMedium",
          "crop_name": "videoHpMedium"
        },
        {
          "rank": 0,
          "subtype": "videoLarge",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoLarge.jpg",
          "height": 507,
          "width": 768,
          "legacy": {},
          "subType": "videoLarge",
          "crop_name": "videoLarge"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine1050",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine1050.jpg",
          "height": 591,
          "width": 1050,
          "legacy": {},
          "subType": "videoSixteenByNine1050",
          "crop_name": "videoSixteenByNine1050"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine150",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine150.jpg",
          "height": 84,
          "width": 150,
          "legacy": {},
          "subType": "videoSixteenByNine150",
          "crop_name": "videoSixteenByNine150"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine225",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine225.jpg",
          "height": 126,
          "width": 225,
          "legacy": {},
          "subType": "videoSixteenByNine225",
          "crop_name": "videoSixteenByNine225"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine3000",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine3000.jpg",
          "height": 1686,
          "width": 3000,
          "legacy": {},
          "subType": "videoSixteenByNine3000",
          "crop_name": "videoSixteenByNine3000"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine310",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine310.jpg",
          "height": 174,
          "width": 310,
          "legacy": {},
          "subType": "videoSixteenByNine310",
          "crop_name": "videoSixteenByNine310"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine390",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine390.jpg",
          "height": 219,
          "width": 390,
          "legacy": {},
          "subType": "videoSixteenByNine390",
          "crop_name": "videoSixteenByNine390"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine480",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine480.jpg",
          "height": 270,
          "width": 480,
          "legacy": {},
          "subType": "videoSixteenByNine480",
          "crop_name": "videoSixteenByNine480"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine495",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine495.jpg",
          "height": 278,
          "width": 495,
          "legacy": {},
          "subType": "videoSixteenByNine495",
          "crop_name": "videoSixteenByNine495"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine540",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine540.jpg",
          "height": 304,
          "width": 540,
          "legacy": {},
          "subType": "videoSixteenByNine540",
          "crop_name": "videoSixteenByNine540"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine600",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine600.jpg",
          "height": 338,
          "width": 600,
          "legacy": {},
          "subType": "videoSixteenByNine600",
          "crop_name": "videoSixteenByNine600"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine768",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine768.jpg",
          "height": 432,
          "width": 768,
          "legacy": {},
          "subType": "videoSixteenByNine768",
          "crop_name": "videoSixteenByNine768"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNine96",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNine96.jpg",
          "height": 54,
          "width": 96,
          "legacy": {},
          "subType": "videoSixteenByNine96",
          "crop_name": "videoSixteenByNine96"
        },
        {
          "rank": 0,
          "subtype": "videoSixteenByNineJumbo1600",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSixteenByNineJumbo1600.jpg",
          "height": 899,
          "width": 1600,
          "legacy": {},
          "subType": "videoSixteenByNineJumbo1600",
          "crop_name": "videoSixteenByNineJumbo1600"
        },
        {
          "rank": 0,
          "subtype": "videoSmall",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoSmall.jpg",
          "height": 281,
          "width": 500,
          "legacy": {},
          "subType": "videoSmall",
          "crop_name": "videoSmall"
        },
        {
          "rank": 0,
          "subtype": "videoThumb",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-videoThumb.jpg",
          "height": 50,
          "width": 75,
          "legacy": {},
          "subType": "videoThumb",
          "crop_name": "videoThumb"
        },
        {
          "rank": 0,
          "subtype": "watch268",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-watch268.jpg",
          "height": 303,
          "width": 272,
          "legacy": {},
          "subType": "watch268",
          "crop_name": "watch268"
        },
        {
          "rank": 0,
          "subtype": "watch308",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-watch308.jpg",
          "height": 348,
          "width": 312,
          "legacy": {},
          "subType": "watch308",
          "crop_name": "watch308"
        },
        {
          "rank": 0,
          "subtype": "windowsTile336H",
          "caption": null,
          "credit": null,
          "type": "image",
          "url": "images/2018/05/27/sports/24mclachlanweb1/24mclachlanweb1-windowsTile336H.jpg",
          "height": 336,
          "width": 694,
          "legacy": {},
          "subType": "windowsTile336H",
          "crop_name": "windowsTile336H"
        }
      ],
      "headline": {
        "main": "Ben McLachlan Rises in Doubles, but a Regular Partner Would Be Nice",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Rising Force in Doubles, Without a Partner",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [
        {
          "name": "subject",
          "value": "Tennis",
          "rank": 1,
          "major": "N"
        },
        {
          "name": "subject",
          "value": "French Open (Tennis)",
          "rank": 2,
          "major": "N"
        },
        {
          "name": "organizations",
          "value": "University of California, Berkeley",
          "rank": 3,
          "major": "N"
        },
        {
          "name": "glocations",
          "value": "Japan",
          "rank": 4,
          "major": "N"
        }
      ],
      "pub_date": "2018-05-26T15:45:04+0000",
      "document_type": "article",
      "new_desk": "Sports",
      "section_name": "Tennis",
      "byline": {
        "original": "By RAVI UBHA",
        "person": [
          {
            "firstname": "Ravi",
            "middlename": null,
            "lastname": "UBHA",
            "qualifier": null,
            "title": null,
            "role": "reported",
            "organization": "",
            "rank": 1
          }
        ],
        "organization": null
      },
      "type_of_material": "News",
      "_id": "5b098104068401528a2affc3",
      "word_count": 1073,
      "score": 0.00086546957,
      "uri": "nyt://article/a4a653fe-e843-55fb-882c-4e90cc19bc41"
    },
    {
      "web_url": "https://www.nytimes.com/aponline/2018/05/26/sports/soccer/ap-soc-wcup-brazil-neymar.html",
      "snippet": "Neymar finished his first full week of training with Brazil on Saturday in apparent good shape ahead of the upcoming World Cup after foot surgery.",
      "blog": {},
      "source": "AP",
      "multimedia": [],
      "headline": {
        "main": "Neymar Appears in Good Shape After Brazil Training Week",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Neymar Appears in Good Shape After Brazil Training Week",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-26T15:30:53+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Soccer",
      "byline": {
        "original": "By THE ASSOCIATED PRESS",
        "person": [],
        "organization": "THE ASSOCIATED PRESS"
      },
      "type_of_material": "News",
      "_id": "5b097db0068401528a2affbe",
      "word_count": 376,
      "score": 0.29622844,
      "uri": "nyt://article/123028f9-9cbe-545e-88e0-6138c227bd52"
    },
    {
      "web_url": "https://www.nytimes.com/aponline/2018/05/26/world/americas/ap-lt-brazil-truckers-strike.html",
      "snippet": "A truckers' strike in Brazil left a patchwork of empty gas stations and barren supermarket shelves Saturday as drivers appeared unmoved by the government's threats to use force or fine people who didn't comply.",
      "blog": {},
      "source": "AP",
      "multimedia": [],
      "headline": {
        "main": "Empty Stores, Shuttered Gas Posts in Brazil Truckers' Strike",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Empty Stores, Shuttered Gas Posts in Brazil Truckers' Strike",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-26T14:51:55+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Americas",
      "byline": {
        "original": "By THE ASSOCIATED PRESS",
        "person": [],
        "organization": "THE ASSOCIATED PRESS"
      },
      "type_of_material": "News",
      "_id": "5b09748d068401528a2affb4",
      "word_count": 650,
      "score": 0.2883079,
      "uri": "nyt://article/94c143ba-79fe-5e4c-991e-f9a910755bd7"
    },
    {
      "web_url": "https://www.nytimes.com/aponline/2018/05/25/sports/baseball/ap-bbo-braves-red-sox.html",
      "snippet": "A surprising roster shakeup didn't disrupt the power surge that has the Boston Red Sox back in first place.",
      "blog": {},
      "source": "AP",
      "multimedia": [],
      "headline": {
        "main": "Betts Hits 17th HR, Red Sox Beat Braves After Cutting Hanley",
        "kicker": null,
        "content_kicker": null,
        "print_headline": "Betts Hits 17th HR, Red Sox Beat Braves After Cutting Hanley",
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "2018-05-26T02:39:50+0000",
      "document_type": "article",
      "new_desk": "None",
      "section_name": "Baseball",
      "byline": {
        "original": "By THE ASSOCIATED PRESS",
        "person": [],
        "organization": "THE ASSOCIATED PRESS"
      },
      "type_of_material": "News",
      "_id": "5b08c8fe068401528a2afefc",
      "word_count": 1016,
      "score": 0.00085417385,
      "uri": "nyt://article/cca6fdfb-ba47-5495-bf2f-e1fc42f4932f"
    }
  ],
  "pages": 0,
}

export const mockSearchOldestArticleResponse = {
  "items": [
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=950DEEDF1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "",
      "print_page": "2",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "Article 11 -- No Title",
        "kicker": "1",
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Article",
      "_id": "4fbfd23e45c1498b0d004db1",
      "word_count": 52,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9C06E7DE1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "",
      "print_page": "4",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "FINANCIAL.",
        "kicker": "1",
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Article",
      "_id": "4fbfd23e45c1498b0d004dab",
      "word_count": 392,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9907E7DE1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "",
      "print_page": "4",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "DIED.",
        "kicker": "1",
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Obituary",
      "_id": "4fbfd23e45c1498b0d004dba",
      "word_count": 21,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9D05E7DE1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "THE UNITED STATES DISTRICT COURT--Before Judge BETTS.--The Grand Jury came into Court with true bills in the following cases, viz: The United States vs. Wm. McIntosh and ten others--For making a revolt on board the ship Columbus. The defendants we...",
      "print_page": "3",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "Article 17 -- No Title; COURT OF GENERAL SESSIONS",
        "kicker": "1",
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Article",
      "_id": "4fbfd23e45c1498b0d004db9",
      "word_count": 335,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9B02EEDF1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "",
      "print_page": "2",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "Article 1 -- No Title",
        "kicker": "1",
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Article",
      "_id": "4fbfd23e45c1498b0d004dc0",
      "word_count": 134,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9807E7DE1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "",
      "print_page": "4",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "MARRIED.",
        "kicker": "1",
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Marriage Announcement",
      "_id": "4fbfd24245c1498b0d004f56",
      "word_count": 27,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9B0DEEDF1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "Our readers have undoubtedly made themselves familiar, through the public journals, with the history and result of the late invasion of Cuba. We shall not, therefore, repeat them. The issue of this attempt will probably prevent any new one, for so...",
      "abstract": "editorial",
      "print_page": "2",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "Cuba.",
        "kicker": null,
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [
        {
          "name": "glocations",
          "value": "CUBA, ISLAND OF",
          "rank": 0,
          "major": null
        }
      ],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Article",
      "_id": "4fbfd24245c1498b0d005098",
      "word_count": 889,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9C0DEEDF1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "Another Mexican Foray is currently talked of at New-Orleans, and rumor is so far explicit as to indicate Tamaulipas, Leon and Coahuila, as the Provinces to be dismembered; and that forces for the expedition are rallying in that city and at sever a...",
      "print_page": "2",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "Article 4 -- No Title",
        "kicker": "1",
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Article",
      "_id": "4fbfd24945c1498b0d005099",
      "word_count": 146,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9E0CEEDF1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "In February, 1849, The Times directed public attention to the desirableness of a transit route from the Atlantic to the Pacific, by way of Lake Nicaragua. At that time we Englishmen possessed every advantage for undertaking it. The enterprise, how...",
      "abstract": "Article in Lond. Examiner on the Nicaragua route",
      "print_page": "2",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "The Nicaragua Route.--England and America.",
        "kicker": null,
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [
        {
          "name": "glocations",
          "value": "NICARAGUA",
          "rank": 0,
          "major": null
        }
      ],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Article",
      "_id": "4fbfd23f45c1498b0d004f43",
      "word_count": 482,
      "score": 1
    },
    {
      "web_url": "https://query.nytimes.com/gst/abstract.html?res=9D02EEDF1430EF33A2575BC1A96F9C946092D7CF",
      "snippet": "The weather was the theme upon which we hinged an item for our morning edition, but we have been forced to forgo the infliction of it upon the public, by the proceedings of the Boston Jubilee, which our special correspondent has forwarded us.  ",
      "print_page": "1",
      "blog": {},
      "source": "The New York Times",
      "multimedia": [],
      "headline": {
        "main": "NEW-YORK CITY.; DEATH OF A BAPTIST MISSIONARY. EXECUTION OF THE TOW CONDESTNED MURDERERS--Between the hours fo 10 and 11 o'clock to-morrow FIRE IN HUDSON-STREET. FIRE IN SPRING-STREET. RUN OVER BY AN ICE CART. DISTURBANCE BETWEEN RIYAL BLACKSMITHS. STEAMERS. \"TREY COME.\" NEW STEAMBOAT LINE. DEATH IN A CELL. DEATH FROM CONYULSIONS. FALSE ALARM. WOMAN POISONED. ACCIDENT TO AN OMNIBES-DRIVER A SAD AND FATAL ACCIDENT. ARREST OF AN ESCAPED COURT CALENDAR",
        "kicker": "1",
        "content_kicker": null,
        "print_headline": null,
        "name": null,
        "seo": null,
        "sub": null
      },
      "keywords": [],
      "pub_date": "1851-09-18T00:03:58Z",
      "document_type": "article",
      "type_of_material": "Front Page",
      "_id": "4fbfd22945c1498b0d004d90",
      "word_count": 2102,
      "score": 1
    }
  ],
  "pages": 0
}